### ISSUE TITLE
Run the project

### ISSUE THREAD

**Issue by Narges1996** [mohamedac29/DSANet#1]
Would you please recommend a command to run this project?
I tried to run DSANet.py and I got this error:
`Traceback (most recent call last):`
   `File "eval_fps.py", line 6, in <module>`
   `from builders.model_builder import build_model`
`ModuleNotFoundError: No module named 'builders.model_builder'`

I installed `builders` but it didn't work.

**Comment by mohamedac29** [comment]
> Would you please recommend a command to run this project? I tried to run DSANet.py and I got this error: `Traceback (most recent call last):` `File "eval_fps.py", line 6, in <module>` `from builders.model_builder import build_model` `ModuleNotFoundError: No module named 'builders.model_builder'`
> 
> I installed `builders` but it didn't work.

Thank you for reminding me of these missing modules. I updated the code by adding training, testing, and the builders modules. Now the code is complete

**Comment by mohamedac29** [comment]
@Narges1996 

Thank you for reminding me of these missing modules. I updated the code by adding training, testing, and the builders modules. Now the code is complete

**Comment by Narges1996** [comment]
@mohamedac29 
Thank you for your response.
Is it possible to be the  same problem for "utils"? 
Because I got this error: 
```
raceback (most recent call last):
  File "/content/DSANet/train.py", line 14, in <module>
    from utils.utils import setup_seed, init_weight, netParams
ModuleNotFoundError: No module named 'utils.utils'
```

**Comment by mohamedac29** [comment]
@Narges1996 
I added the utils folder you can run the code now
